const names = require('./4-names')
const sayHi = require('./5-utilis')
const data = require('./6-alternative flavours')
require('./7-mind grenade')
sayHi(names.lance)
sayHi(names.Kevin)
sayHi(names.susan) 
